#!/usr/bin/python

import string
import os
import argparse

parser = argparse.ArgumentParser(description='genpass: a tool for generating a password')
parser.add_argument('-l','--length', help='Password length', required=True)
args = parser.parse_args()
chars = string.letters + string.digits + '+/'
assert 256 % len(chars) == 0


def genpass(charlen):
    if args.length is not None:
        print ''.join(chars[ord(c) % len(chars)] for c in os.urandom(int(charlen)))

def doMain():

    genpass(args.length)

if __name__ == "__main__":
    doMain()

